<?php

namespace SosBundle\Repository;

/**
 * AnglaisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnglaisRepository extends \Doctrine\ORM\EntityRepository
{
}
