<?php

namespace SosBundle\Repository;

/**
 * ContratCritereRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContratCritereRepository extends \Doctrine\ORM\EntityRepository
{
}
