<?php

namespace SosBundle\Repository;

/**
 * CursusScolaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CursusScolaireRepository extends \Doctrine\ORM\EntityRepository
{
}
