<?php

namespace SosBundle\Repository;

/**
 * NiveauAnglaisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NiveauAnglaisRepository extends \Doctrine\ORM\EntityRepository
{
}
