<?php

namespace SosBundle\Repository;

/**
 * PosteRechercheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PosteRechercheRepository extends \Doctrine\ORM\EntityRepository
{
}
