<?php

namespace SosBundle\Repository;

/**
 * PosteCritereRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PosteCritereRepository extends \Doctrine\ORM\EntityRepository
{
}
