<?php

namespace SosBundle\Repository;

/**
 * RaisonSuppressionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RaisonSuppressionRepository extends \Doctrine\ORM\EntityRepository
{
}
