<?php

namespace SosBundle\Repository;

/**
 * FormationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecommandationRepository extends \Doctrine\ORM\EntityRepository
{
}
