<?php

namespace SosBundle\Repository;

/**
 * SuppressionCompteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SuppressionCompteRepository extends \Doctrine\ORM\EntityRepository
{
}
