<?php

namespace SosBundle\Repository;

/**
 * UserCritereRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserCritereRepository extends \Doctrine\ORM\EntityRepository
{
}
