index:
    path:     /
    defaults: { _controller: SosBundle:Default:index }

cgv:
    path:     /cgv
    defaults: { _controller: SosBundle:Default:cgv }

contact:
    path:     /contact
    defaults: { _controller: SosBundle:Default:contact }

information:
    path:     /information
    defaults: { _controller: SosBundle:Default:information }
  
profil:
    path:     /profil
    defaults: { _controller: SosBundle:Default:profil }

ville:
    path:     /search/ville
    defaults: { _controller: SosBundle:Search:ville }

classification:
    path:     /search/classification
    defaults: { _controller: SosBundle:Search:classification }

secteur:
    path:     /search/secteur
    defaults: { _controller: SosBundle:Search:secteur }

service:
    path:     /search/service
    defaults: { _controller: SosBundle:Search:service }

poste:
    path:     /search/poste
    defaults: { _controller: SosBundle:Search:poste }

contrat:
    path:     /search/contrat
    defaults: { _controller: SosBundle:Search:contrat }

duree:
    path:     /search/duree
    defaults: { _controller: SosBundle:Search:duree }

cursus:
    path:     /search/cursus
    defaults: { _controller: SosBundle:Search:cursus }

formation:
    path:     /search/formation
    defaults: { _controller: SosBundle:Search:formation }

experience:
    path:     /search/experience
    defaults: { _controller: SosBundle:Search:experience }

anglais:
    path:     /search/anglais
    defaults: { _controller: SosBundle:Search:anglais }

date:
    path:     /search/date
    defaults: { _controller: SosBundle:Search:date }

resultat:
    path:     /search/resultat
    defaults: { _controller: SosBundle:Search:resultat }

demandeCv:
    path:     /search/demandeCv
    defaults: { _controller: SosBundle:Search:demandeCv }

imprimer:
    path:     /search/imprimer
    defaults: { _controller: SosBundle:Search:imprimer }

messageCv:
    path:     /messageCv
    defaults: { _controller: SosBundle:Search:messageCv }

message5J:
    path:     /message5J
    defaults: { _controller: SosBundle:Search:message5J }

dashboard:
    path:     /dashboard
    defaults: { _controller: SosBundle:Default:dashboard }

abonnement:
    path:     /abonnement
    defaults: { _controller: SosBundle:Default:abonnement }

dashboard_admin:
    path:     /dashboard_admin
    defaults: { _controller: SosBundle:Default:dashboardAdmin }

demandeRecommandation:
    path:     /demandeRecommandation
    defaults: { _controller: SosBundle:Admin:demandeRecommandation }

signalement_profil:
    path:     /signalement_profil
    defaults: { _controller: SosBundle:Default:signalementProfil }

cron_user:
    path:     /cron_user
    defaults: { _controller: SosBundle:Default:cronuser }

# INFORMATION USER START

usercriteres_step_1:
    path: /usercriteres/step1
    defaults: { _controller: SosBundle:UserCriteres:step1}

usercriteres_step_2:
    path: /usercriteres/step2
    defaults: { _controller: SosBundle:UserCriteres:step2}

usercriteres_step_3:
    path: /usercriteres/step3    
    defaults: { _controller: SosBundle:UserCriteres:step3}

usercriteres_step_4:
    path: /usercriteres/step4    
    defaults: { _controller: SosBundle:UserCriteres:step4}

usercriteres_step_5:
    path: /usercriteres/step5    
    defaults: { _controller: SosBundle:UserCriteres:step5}

usercriteres_step_6:
    path: /usercriteres/step6    
    defaults: { _controller: SosBundle:UserCriteres:step6}

usercriteres_step_7:
    path: /usercriteres/step7  
    defaults: { _controller: SosBundle:UserCriteres:step7}

usercriteres_step_8:
    path: /usercriteres/step8
    defaults: { _controller: SosBundle:UserCriteres:step8}

usercriteres_step_9:
    path: /usercriteres/step9  
    defaults: { _controller: SosBundle:UserCriteres:step9}

edit_disponibilite:
    path: /usercriteres/edit/disponibilites
    defaults: { _controller: SosBundle:UserCriteres:step9}

modification_usercriteres:
    path: /usercriteres/edit
    defaults: { _controller: SosBundle:UserCriteres:userCriteresModification}

modification_disponibilites:
    path: /usercriteres/disponibilites
    defaults: { _controller: SosBundle:UserCriteres:disponibiliteModification}

modification_contrat:
    path: /usercriteres/contrats
    defaults: { _controller: SosBundle:UserCriteres:modificationContrats}

# INFORMATION USER START


# USER
public_profil:
    path: /user/{id}
    defaults: { _controller: SosBundle:User:publicProfil}

delete_user:
    path: /delete
    defaults: { _controller: SosBundle:User:deleteUser}
    options:
        expose: true

delete_confirmed:
    path: /delete/confirmed
    defaults: { _controller: SosBundle:User:deleteConfirmationUser}

mesrecommandations:
    path:     /mesrecommandations
    defaults: { _controller: SosBundle:User:mesrecommandations}

validationrecommandations:
    path:    /validation/{code}/{id}
    defaults: { _controller: SosBundle:User:validation}

# ADMIN
recommandations:
    path:     /admin/recommandations
    defaults: { _controller: SosBundle:Admin:recommandations }
utilisateurs:
    path:     /admin/utilisateurs
    defaults: { _controller: SosBundle:Admin:utilisateurs }
statistiques:
    path:     /admin/statistiques
    defaults: { _controller: SosBundle:Admin:statistiques }
signalements:
    path:     /admin/signalements
    defaults: { _controller: SosBundle:Admin:signalements }
validation:
    path:     /admin/validation
    defaults: { _controller: SosBundle:Admin:validation }
recommandationsutilisateurs:
    path:     /admin/recommandationsutilisateurs
    defaults: { _controller: SosBundle:Admin:recommandationsByUser }

#MEDAILLE
medaille:
    path:     /medaille/{id}
    defaults: { _controller: SosBundle:Admin:medaille}

#Paiement
payment:
    path:    /payment
    defaults: { _controller: SosBundle:Orders:payment }
success:
    path:    /payment/success/{id}
    defaults: { _controller: SosBundle:Orders:success }
error:
    path:    /payment/error/{id}
    defaults: { _controller: SosBundle:Orders:error }
